---
# Playbook Ansible pour déployer Velya en production
# Usage: ansible-playbook deploy-velya.yml -i inventory.ini

- name: Déployer Velya sur serveur production
  hosts: production
  become: yes
  vars:
    app_name: velya
    app_path: /opt/velya
    app_user: velya
    app_group: velya
    domain: velya.ca
    api_domain: api.velya.ca

  tasks:
    # Étape 1: Prérequis système
    - name: "Étape 1: Mise à jour du système"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: system

    - name: "Installation des paquets essentiels"
      apt:
        name:
          - curl
          - wget
          - git
          - htop
          - vim
          - net-tools
          - ufw
          - fail2ban
        state: present
      tags: system

    # Étape 2: Installation Docker
    - name: "Installation de Docker"
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh
      args:
        creates: /usr/bin/docker
      tags: docker

    - name: "Installation de Docker Compose"
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose
      tags: docker

    - name: "Ajouter utilisateur courant au groupe docker"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags: docker

    # Étape 3: Firewall
    - name: "Configuration UFW - Activer"
      ufw:
        state: enabled
        policy: deny
        direction: incoming
      tags: firewall

    - name: "Configuration UFW - SSH"
      ufw:
        rule: allow
        port: '22'
        proto: tcp
      tags: firewall

    - name: "Configuration UFW - HTTP"
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      tags: firewall

    - name: "Configuration UFW - HTTPS"
      ufw:
        rule: allow
        port: '443'
        proto: tcp
      tags: firewall

    # Étape 4: Créer utilisateur d'application
    - name: "Créer utilisateur {{ app_user }}"
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        home: "{{ app_path }}"
        createhome: yes
      tags: users

    - name: "Ajouter utilisateur au groupe docker"
      user:
        name: "{{ app_user }}"
        groups: docker
        append: yes
      tags: users

    # Étape 5: Cloner le repository
    - name: "Créer répertoire d'application"
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      tags: app

    - name: "Cloner le repository"
      git:
        repo: "https://github.com/kevinmulamba/cleaningApp-frontend.git"
        dest: "{{ app_path }}"
        version: rename-cleaningapp-to-velya
        key_file: /home/{{ ansible_user }}/.ssh/id_rsa
      become_user: "{{ app_user }}"
      tags: app

    # Étape 6: Configuration environnement
    - name: "Copier configuration de production"
      copy:
        src: .env.production
        dest: "{{ app_path }}/.env.production"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0600'
      tags: config

    - name: "Créer répertoire SSL"
      file:
        path: "{{ app_path }}/ssl"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0700'
      tags: ssl

    # Étape 7: Certificats Let's Encrypt
    - name: "Installation de Certbot"
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      tags: ssl

    - name: "Générer certificats SSL"
      shell: |
        certbot certonly --standalone \
          -d {{ domain }} \
          -d {{ api_domain }} \
          -m admin@{{ domain }} \
          --agree-tos \
          --non-interactive
      args:
        creates: /etc/letsencrypt/live/{{ domain }}/cert.pem
      tags: ssl

    - name: "Copier certificats"
      shell: |
        cp /etc/letsencrypt/live/{{ domain }}/fullchain.pem {{ app_path }}/ssl/cert.pem
        cp /etc/letsencrypt/live/{{ domain }}/privkey.pem {{ app_path }}/ssl/key.pem
        chown {{ app_user }}:{{ app_group }} {{ app_path }}/ssl/*
        chmod 600 {{ app_path }}/ssl/key.pem
      tags: ssl

    # Étape 8: Google Service Account
    - name: "Copier Google Service Account"
      copy:
        src: google-service-account.json
        dest: "{{ app_path }}/backend/config/google-service-account.json"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0600'
      tags: config

    # Étape 9: Déployer avec Docker
    - name: "Build des images Docker"
      shell: docker-compose -f docker-compose.prod.yml build
      args:
        chdir: "{{ app_path }}"
      become_user: "{{ app_user }}"
      tags: deploy

    - name: "Démarrer les services"
      shell: docker-compose -f docker-compose.prod.yml up -d
      args:
        chdir: "{{ app_path }}"
      become_user: "{{ app_user }}"
      tags: deploy

    # Étape 10: Vérifications
    - name: "Attendre le démarrage des services"
      pause:
        seconds: 30
      tags: deploy

    - name: "Vérifier MongoDB"
      shell: docker-compose -f docker-compose.prod.yml exec -T mongodb mongosh -u velya_admin -p --eval "db.adminCommand('ping')"
      args:
        chdir: "{{ app_path }}"
      become_user: "{{ app_user }}"
      register: mongo_check
      tags: verify

    - name: "Vérifier Backend"
      uri:
        url: "http://localhost:5001/api/health"
        method: GET
      register: backend_check
      tags: verify

    # Étape 11: Logs
    - name: "Afficher status des services"
      shell: docker-compose -f docker-compose.prod.yml ps
      args:
        chdir: "{{ app_path }}"
      become_user: "{{ app_user }}"
      register: compose_ps
      tags: logs

    - name: "Status des services"
      debug:
        msg: "{{ compose_ps.stdout_lines }}"
      tags: logs

    # Étape 12: Renouvellement certificats automatique
    - name: "Créer script de renouvellement"
      copy:
        content: |
          #!/bin/bash
          certbot renew --quiet
          cd {{ app_path }}
          docker-compose -f docker-compose.prod.yml restart nginx
        dest: /usr/local/bin/renew-velya-certs.sh
        mode: '0755'
      tags: ssl

    - name: "Créer systemd timer pour certificats"
      copy:
        content: |
          [Unit]
          Description=Renouveler certificats Velya quotidiennement
          After=network.target

          [Timer]
          OnBootSec=1h
          OnUnitActiveSec=1d
          Persistent=true

          [Install]
          WantedBy=timers.target
        dest: /etc/systemd/system/renew-velya-certs.timer
      tags: ssl

    - name: "Activer le timer systemd"
      systemd:
        name: renew-velya-certs.timer
        enabled: yes
        state: started
        daemon_reload: yes
      tags: ssl

  handlers:
    - name: Redémarrer docker
      systemd:
        name: docker
        state: restarted

post_tasks:
  - name: "✅ Déploiement terminé!"
    debug:
      msg: |
        Velya a été déployé avec succès!
        
        🌐 URLs:
          Frontend: https://{{ domain }}
          API: https://{{ api_domain }}
        
        📊 Status: docker-compose -f docker-compose.prod.yml ps
        📝 Logs: docker-compose -f docker-compose.prod.yml logs -f
        🔄 Redémarrer: docker-compose -f docker-compose.prod.yml restart
